version: "3.8"

services:
  trt-bewerbungsliste-backend:
    build: .
    container_name: trt-bewerbungsliste-backend
    volumes:
      - /opt/trt.Bewerbungsliste/data:/app/data
    environment:
      - BEWERBUNG_DB_PATH=/app/data/bewerbungen.db
    ports:
      - "8090:5000"
    restart: unless-stopped
